-- ============================================================
-- LearnTrack v2 – Production DDL (PostgreSQL / Supabase)
-- UUID edition – user_id is UUID matching Supabase auth.uid()
-- ============================================================
-- Key changes from integer-PK version:
--   • users.user_id  → UUID (references auth.users from Supabase Auth)
--   • All FK columns that pointed at users.user_id are now UUID
--   • SERIAL removed from user_id; all other PKs stay SERIAL INT
--   • RLS policies use auth.uid() directly (no ::int cast)
--   • auth.uid() returns UUID — now matches users.user_id natively
-- ============================================================

-- ── Safe re-run teardown (reverse dependency order) ──────────────────────────
DROP MATERIALIZED VIEW IF EXISTS mv_performance_summary CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_active_students CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_underperforming_students CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_skipped_content CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_completion_rates CASCADE;
DROP TABLE IF EXISTS quiz_answers         CASCADE;
DROP TABLE IF EXISTS question_options     CASCADE;
DROP TABLE IF EXISTS quiz_questions       CASCADE;
DROP TABLE IF EXISTS question_types       CASCADE;
DROP TABLE IF EXISTS quiz_attempts        CASCADE;
DROP TABLE IF EXISTS quiz                 CASCADE;
DROP TABLE IF EXISTS content_progress     CASCADE;
DROP TABLE IF EXISTS user_sessions        CASCADE;
DROP TABLE IF EXISTS activity_log         CASCADE;
DROP TABLE IF EXISTS activity_types       CASCADE;
DROP TABLE IF EXISTS content              CASCADE;
DROP TABLE IF EXISTS content_types        CASCADE;
DROP TABLE IF EXISTS enrollments          CASCADE;
DROP TABLE IF EXISTS enrollment_statuses  CASCADE;
DROP TABLE IF EXISTS courses              CASCADE;
DROP TABLE IF EXISTS instructors          CASCADE;
DROP TABLE IF EXISTS users               CASCADE;

-- ────────────────────────────────────────────────────────────────────────────
-- TIER 1 – ROOT ENTITIES
-- ────────────────────────────────────────────────────────────────────────────

-- ── 1. USERS ─────────────────────────────────────────────────────────────────
-- user_id is UUID and mirrors auth.users(id) from Supabase Auth.
-- Do NOT use SERIAL here — the UUID is generated by Supabase on signup.
-- Insert into this table is triggered by a Supabase Auth hook (see below).
CREATE TABLE users (
  user_id    UUID         PRIMARY KEY,   -- matches auth.users.id (Supabase)
  full_name  VARCHAR(100) NOT NULL,
  email      VARCHAR(150) NOT NULL UNIQUE,
  password   VARCHAR(255) NOT NULL,      -- hashed; mirrored from auth layer
  role       VARCHAR(20)  NOT NULL DEFAULT 'student'
                          CHECK (role IN ('student', 'instructor', 'admin')),
  bio        TEXT,
  avatar_url VARCHAR(500),
  is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN users.user_id IS
  'UUID from Supabase auth.users.id. Created by Supabase on registration.';
COMMENT ON COLUMN users.deleted_at IS
  'NULL = active. Soft delete — filter with WHERE deleted_at IS NULL.';

-- ────────────────────────────────────────────────────────────────────────────
-- TIER 2 – LOOKUP / REFERENCE TABLES (all use SERIAL INT PKs — unchanged)
-- ────────────────────────────────────────────────────────────────────────────

-- ── 2. ACTIVITY_TYPES ────────────────────────────────────────────────────────
CREATE TABLE activity_types (
  type_id   SERIAL      PRIMARY KEY,
  type_name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO activity_types (type_name) VALUES
  ('play'), ('pause'), ('skip'), ('seek'), ('complete');

-- ── 3. CONTENT_TYPES ─────────────────────────────────────────────────────────
CREATE TABLE content_types (
  type_id   SERIAL      PRIMARY KEY,
  type_name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO content_types (type_name) VALUES
  ('video'), ('document'), ('quiz');

-- ── 4. ENROLLMENT_STATUSES ───────────────────────────────────────────────────
CREATE TABLE enrollment_statuses (
  status_id   SERIAL      PRIMARY KEY,
  status_name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO enrollment_statuses (status_name) VALUES
  ('active'), ('completed'), ('dropped');

-- ── 5. QUESTION_TYPES ────────────────────────────────────────────────────────
CREATE TABLE question_types (
  type_id     SERIAL       PRIMARY KEY,
  type_name   VARCHAR(50)  NOT NULL UNIQUE,
  description VARCHAR(200)
);

INSERT INTO question_types (type_name, description) VALUES
  ('mcq',        'Multiple choice – one or more correct options'),
  ('true_false', 'Binary choice – exactly two options');

-- ────────────────────────────────────────────────────────────────────────────
-- TIER 3 – INSTRUCTOR PROFILE
-- ────────────────────────────────────────────────────────────────────────────

-- ── 6. INSTRUCTORS ───────────────────────────────────────────────────────────
-- user_id FK is now UUID to match users.user_id
CREATE TABLE instructors (
  instructor_id SERIAL       PRIMARY KEY,
  user_id       UUID         NOT NULL UNIQUE
                             REFERENCES users(user_id) ON DELETE CASCADE,
  department    VARCHAR(100),
  qualification VARCHAR(200),
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Trigger: only instructor/admin users can have an instructors row
CREATE OR REPLACE FUNCTION check_instructor_role()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM users
    WHERE user_id = NEW.user_id
      AND role IN ('instructor', 'admin')
      AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'User % does not have instructor or admin role', NEW.user_id;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_check_instructor_role
  BEFORE INSERT OR UPDATE ON instructors
  FOR EACH ROW EXECUTE FUNCTION check_instructor_role();

-- Auto-provision instructors profile whenever a user is instructor/admin.
-- This removes the need for manual INSERTs into instructors.
CREATE OR REPLACE FUNCTION ensure_instructor_profile()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.role IN ('instructor', 'admin') AND NEW.deleted_at IS NULL THEN
    INSERT INTO instructors (user_id)
    VALUES (NEW.user_id)
    ON CONFLICT (user_id) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ensure_instructor_profile ON users;
CREATE TRIGGER trg_ensure_instructor_profile
  AFTER INSERT OR UPDATE OF role, deleted_at ON users
  FOR EACH ROW
  EXECUTE FUNCTION ensure_instructor_profile();

-- ────────────────────────────────────────────────────────────────────────────
-- TIER 4 – COURSES AND CONTENT
-- ────────────────────────────────────────────────────────────────────────────

-- ── 7. COURSES ───────────────────────────────────────────────────────────────
CREATE TABLE courses (
  course_id     SERIAL       PRIMARY KEY,
  instructor_id INT          NOT NULL
                             REFERENCES instructors(instructor_id)
                             ON DELETE RESTRICT,
  title         VARCHAR(200) NOT NULL,
  description   TEXT,
  category      VARCHAR(100),
  thumbnail_url VARCHAR(500),
  is_published  BOOLEAN      NOT NULL DEFAULT FALSE,
  deleted_at    TIMESTAMPTZ,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_courses_instructor ON courses(instructor_id);
CREATE INDEX idx_courses_category   ON courses(category);
CREATE INDEX idx_courses_published  ON courses(is_published) WHERE deleted_at IS NULL;

-- ── 8. ENROLLMENTS ───────────────────────────────────────────────────────────
-- user_id is now UUID
CREATE TABLE enrollments (
  enrollment_id SERIAL      PRIMARY KEY,
  user_id       UUID        NOT NULL REFERENCES users(user_id)    ON DELETE CASCADE,
  course_id     INT         NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
  status_id     INT         NOT NULL
                            REFERENCES enrollment_statuses(status_id)
                            ON DELETE RESTRICT
                            DEFAULT 1,
  enrolled_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, course_id)
);

CREATE INDEX idx_enrollments_course ON enrollments(course_id);
CREATE INDEX idx_enrollments_user   ON enrollments(user_id);

-- ── 9. CONTENT ───────────────────────────────────────────────────────────────
CREATE TABLE content (
  content_id      SERIAL       PRIMARY KEY,
  course_id       INT          NOT NULL REFERENCES courses(course_id)     ON DELETE CASCADE,
  content_type_id INT          NOT NULL REFERENCES content_types(type_id) ON DELETE RESTRICT,
  title           VARCHAR(200) NOT NULL,
  content_url     VARCHAR(1000),
  content_body    TEXT,
  duration_sec    INT          CHECK (duration_sec > 0),
  sort_order      INT          NOT NULL DEFAULT 0,
  is_published    BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_content_course ON content(course_id);

-- ────────────────────────────────────────────────────────────────────────────
-- TIER 5 – ACTIVITY TRACKING
-- ────────────────────────────────────────────────────────────────────────────

-- ── 10. ACTIVITY_LOG ─────────────────────────────────────────────────────────
-- user_id is now UUID
CREATE TABLE activity_log (
  log_id     SERIAL      PRIMARY KEY,
  user_id    UUID        NOT NULL REFERENCES users(user_id)      ON DELETE CASCADE,
  content_id INT         NOT NULL REFERENCES content(content_id) ON DELETE CASCADE,
  type_id    INT         NOT NULL REFERENCES activity_types(type_id) ON DELETE RESTRICT,
  watch_time INT         NOT NULL DEFAULT 0 CHECK (watch_time >= 0),
  event_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_activity_user     ON activity_log(user_id);
CREATE INDEX idx_activity_content  ON activity_log(content_id);
CREATE INDEX idx_activity_event_at ON activity_log(event_at DESC);

-- ── 11. CONTENT_PROGRESS ─────────────────────────────────────────────────────
-- user_id is now UUID
CREATE TABLE content_progress (
  progress_id      SERIAL       PRIMARY KEY,
  user_id          UUID         NOT NULL REFERENCES users(user_id)      ON DELETE CASCADE,
  content_id       INT          NOT NULL REFERENCES content(content_id) ON DELETE CASCADE,
  progress_percent NUMERIC(5,2) NOT NULL DEFAULT 0
                                CHECK (progress_percent BETWEEN 0 AND 100),
  last_watched_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, content_id)
);

CREATE INDEX idx_progress_user ON content_progress(user_id);

-- ────────────────────────────────────────────────────────────────────────────
-- TIER 6 – QUIZ SYSTEM
-- ────────────────────────────────────────────────────────────────────────────

-- ── 12. QUIZ ─────────────────────────────────────────────────────────────────
CREATE TABLE quiz (
  quiz_id        SERIAL       PRIMARY KEY,
  course_id      INT          NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
  title          VARCHAR(200) NOT NULL,
  time_limit_min INT          CHECK (time_limit_min > 0),
  pass_score     NUMERIC(5,2) NOT NULL DEFAULT 50
                              CHECK (pass_score BETWEEN 0 AND 100),
  allow_multiple BOOLEAN      NOT NULL DEFAULT TRUE,
  is_published   BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_quiz_course ON quiz(course_id);

-- ── 13. QUIZ_QUESTIONS ───────────────────────────────────────────────────────
CREATE TABLE quiz_questions (
  question_id      SERIAL       PRIMARY KEY,
  quiz_id          INT          NOT NULL REFERENCES quiz(quiz_id)           ON DELETE CASCADE,
  question_type_id INT          NOT NULL REFERENCES question_types(type_id) ON DELETE RESTRICT,
  question_text    TEXT         NOT NULL,
  sort_order       INT          NOT NULL DEFAULT 0,
  points           NUMERIC(5,2) NOT NULL DEFAULT 1 CHECK (points > 0),
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_questions_quiz ON quiz_questions(quiz_id);

-- ── 14. QUESTION_OPTIONS ─────────────────────────────────────────────────────
CREATE TABLE question_options (
  option_id   SERIAL       PRIMARY KEY,
  question_id INT          NOT NULL REFERENCES quiz_questions(question_id) ON DELETE CASCADE,
  option_text VARCHAR(500) NOT NULL,
  is_correct  BOOLEAN      NOT NULL DEFAULT FALSE,
  sort_order  INT          NOT NULL DEFAULT 0
);

CREATE INDEX idx_options_question ON question_options(question_id);

-- ── 15. QUIZ_ATTEMPTS ────────────────────────────────────────────────────────
-- user_id is now UUID
CREATE TABLE quiz_attempts (
  attempt_id   SERIAL       PRIMARY KEY,
  user_id      UUID         NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  quiz_id      INT          NOT NULL REFERENCES quiz(quiz_id)  ON DELETE CASCADE,
  score        NUMERIC(5,2) NOT NULL CHECK (score BETWEEN 0 AND 100),
  passed       BOOLEAN      NOT NULL DEFAULT FALSE,
  attempt_date TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_attempt_user ON quiz_attempts(user_id);
CREATE INDEX idx_attempt_quiz ON quiz_attempts(quiz_id);

-- ── 16. QUIZ_ANSWERS ─────────────────────────────────────────────────────────
CREATE TABLE quiz_answers (
  answer_id   SERIAL  PRIMARY KEY,
  attempt_id  INT     NOT NULL REFERENCES quiz_attempts(attempt_id)   ON DELETE CASCADE,
  question_id INT     NOT NULL REFERENCES quiz_questions(question_id) ON DELETE CASCADE,
  option_id   INT     NOT NULL REFERENCES question_options(option_id) ON DELETE CASCADE,
  is_correct  BOOLEAN NOT NULL,
  UNIQUE (attempt_id, question_id)
);

CREATE INDEX idx_answers_attempt ON quiz_answers(attempt_id);

-- ────────────────────────────────────────────────────────────────────────────
-- TIER 7 – SESSION MANAGEMENT
-- ────────────────────────────────────────────────────────────────────────────

-- ── 17. USER_SESSIONS ────────────────────────────────────────────────────────
-- user_id is now UUID
CREATE TABLE user_sessions (
  session_id SERIAL       PRIMARY KEY,
  user_id    UUID         NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  token_hash VARCHAR(64)  NOT NULL,   -- SHA-256 hex digest = exactly 64 chars
  login_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  logout_at  TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  ip_address INET,
  user_agent TEXT
);

CREATE INDEX idx_session_user       ON user_sessions(user_id);
CREATE INDEX idx_session_token_hash ON user_sessions(token_hash);
CREATE INDEX idx_session_active     ON user_sessions(expires_at)
  WHERE logout_at IS NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- TIER 8 – MATERIALIZED VIEW (analytics)
-- ────────────────────────────────────────────────────────────────────────────

-- ── 18. MV_PERFORMANCE_SUMMARY ───────────────────────────────────────────────
CREATE MATERIALIZED VIEW mv_performance_summary AS
SELECT
  e.user_id,                                                        -- UUID
  e.course_id,
  COALESCE(SUM(al.watch_time), 0)                   AS total_watch_sec,
  COALESCE(ROUND(AVG(qa.score)::NUMERIC, 2), 0)     AS avg_quiz_score,
  COALESCE(ROUND(AVG(cp.progress_percent)::NUMERIC, 2), 0) AS completion_pct,
  NOW()                                             AS last_refreshed
FROM enrollments e
LEFT JOIN content c        ON c.course_id  = e.course_id
LEFT JOIN activity_log al  ON al.content_id = c.content_id AND al.user_id = e.user_id
LEFT JOIN content_progress cp ON cp.content_id = c.content_id AND cp.user_id = e.user_id
LEFT JOIN quiz q            ON q.course_id  = e.course_id
LEFT JOIN quiz_attempts qa  ON qa.quiz_id   = q.quiz_id    AND qa.user_id = e.user_id
GROUP BY e.user_id, e.course_id
WITH DATA;

CREATE UNIQUE INDEX idx_mv_perf_summary
  ON mv_performance_summary(user_id, course_id);

COMMENT ON MATERIALIZED VIEW mv_performance_summary IS
  'Refresh: REFRESH MATERIALIZED VIEW CONCURRENTLY mv_performance_summary;
   Schedule via pg_cron or Supabase Edge Function cron (every 15-60 min).';

-- ── 19. MV_ACTIVE_STUDENTS ───────────────────────────────────────────────────
CREATE MATERIALIZED VIEW mv_active_students AS
SELECT
  al.user_id,
  u.full_name,
  COALESCE(SUM(al.watch_time), 0) AS total_watch_sec,
  MAX(al.event_at) AS last_event_at
FROM activity_log al
JOIN users u ON u.user_id = al.user_id
WHERE u.role = 'student'
GROUP BY al.user_id, u.full_name
WITH DATA;

CREATE UNIQUE INDEX idx_mv_active_students_user
  ON mv_active_students(user_id);
CREATE INDEX idx_mv_active_students_watch
  ON mv_active_students(total_watch_sec DESC);

-- ── 20. MV_UNDERPERFORMING_STUDENTS ──────────────────────────────────────────
CREATE MATERIALIZED VIEW mv_underperforming_students AS
SELECT
  qa.user_id,
  u.full_name,
  ROUND(AVG(qa.score)::NUMERIC, 2) AS avg_score,
  COUNT(*) AS attempts_count
FROM quiz_attempts qa
JOIN users u ON u.user_id = qa.user_id
GROUP BY qa.user_id, u.full_name
WITH DATA;

CREATE UNIQUE INDEX idx_mv_underperforming_user
  ON mv_underperforming_students(user_id);
CREATE INDEX idx_mv_underperforming_avg
  ON mv_underperforming_students(avg_score);

-- ── 21. MV_SKIPPED_CONTENT ───────────────────────────────────────────────────
CREATE MATERIALIZED VIEW mv_skipped_content AS
SELECT
  al.content_id,
  c.title,
  c.course_id,
  COUNT(*)::INT AS skip_count
FROM activity_log al
JOIN activity_types at ON at.type_id = al.type_id
JOIN content c ON c.content_id = al.content_id
WHERE at.type_name = 'skip'
GROUP BY al.content_id, c.title, c.course_id
WITH DATA;

CREATE UNIQUE INDEX idx_mv_skipped_content_id
  ON mv_skipped_content(content_id);
CREATE INDEX idx_mv_skipped_content_course
  ON mv_skipped_content(course_id);
CREATE INDEX idx_mv_skipped_content_count
  ON mv_skipped_content(skip_count DESC);

-- ── 22. MV_COMPLETION_RATES ──────────────────────────────────────────────────
CREATE MATERIALIZED VIEW mv_completion_rates AS
SELECT
  cp.user_id,
  u.full_name,
  c.course_id,
  ROUND(AVG(cp.progress_percent)::NUMERIC, 2) AS avg_completion_pct,
  COUNT(*)::INT AS content_items
FROM content_progress cp
JOIN users u ON u.user_id = cp.user_id
JOIN content c ON c.content_id = cp.content_id
GROUP BY cp.user_id, u.full_name, c.course_id
WITH DATA;

CREATE UNIQUE INDEX idx_mv_completion_rates_user_course
  ON mv_completion_rates(user_id, course_id);
CREATE INDEX idx_mv_completion_rates_course
  ON mv_completion_rates(course_id);
CREATE INDEX idx_mv_completion_rates_pct
  ON mv_completion_rates(avg_completion_pct DESC);

-- Utility function to refresh all analytics materialized views.
CREATE OR REPLACE FUNCTION refresh_analytics_views()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  REFRESH MATERIALIZED VIEW mv_performance_summary;
  REFRESH MATERIALIZED VIEW mv_active_students;
  REFRESH MATERIALIZED VIEW mv_underperforming_students;
  REFRESH MATERIALIZED VIEW mv_skipped_content;
  REFRESH MATERIALIZED VIEW mv_completion_rates;
END;
$$;

-- Backward-compatible wrapper used by existing API/tests.
CREATE OR REPLACE FUNCTION refresh_performance_summary()
RETURNS void
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT refresh_analytics_views();
$$;

-- ────────────────────────────────────────────────────────────────────────────
-- HELPER TRIGGERS
-- ────────────────────────────────────────────────────────────────────────────

-- updated_at auto-stamp
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DO $$
DECLARE tbl TEXT;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'users','instructors','courses','enrollments','content','quiz'
  ] LOOP
    EXECUTE format(
      'CREATE TRIGGER trg_set_updated_at
       BEFORE UPDATE ON %I
       FOR EACH ROW EXECUTE FUNCTION set_updated_at()', tbl
    );
  END LOOP;
END;
$$;

-- ────────────────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY (RLS)
-- auth.uid() returns UUID — now matches users.user_id directly (no cast)
-- ────────────────────────────────────────────────────────────────────────────

ALTER TABLE users            ENABLE ROW LEVEL SECURITY;
ALTER TABLE instructors      ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses          ENABLE ROW LEVEL SECURITY;
ALTER TABLE enrollments      ENABLE ROW LEVEL SECURITY;
ALTER TABLE content          ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_log     ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_attempts    ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_answers     ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions    ENABLE ROW LEVEL SECURITY;

-- Users can read/update only their own profile
CREATE POLICY users_self_rw ON users
  USING      (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Backend service-role access (used by server-side registration/login flows)
CREATE POLICY users_service_role_all ON users
  FOR ALL TO service_role
  USING (TRUE)
  WITH CHECK (TRUE);

-- Published, non-deleted courses are readable by all authenticated users
CREATE POLICY courses_published_read ON courses
  FOR SELECT USING (is_published = TRUE AND deleted_at IS NULL);

-- Instructors can manage their own courses
CREATE POLICY courses_instructor_write ON courses
  FOR ALL USING (
    instructor_id IN (
      SELECT instructor_id FROM instructors
      WHERE user_id = auth.uid()
    )
  );

-- Content is readable when published, and manageable by course owner instructor/admin.
CREATE POLICY content_published_read ON content
  FOR SELECT USING (
    is_published = TRUE
    OR course_id IN (
      SELECT c.course_id
      FROM courses c
      JOIN instructors i ON i.instructor_id = c.instructor_id
      WHERE i.user_id = auth.uid()
    )
  );

CREATE POLICY content_instructor_write ON content
  FOR ALL USING (
    course_id IN (
      SELECT c.course_id
      FROM courses c
      JOIN instructors i ON i.instructor_id = c.instructor_id
      WHERE i.user_id = auth.uid()
    )
  )
  WITH CHECK (
    course_id IN (
      SELECT c.course_id
      FROM courses c
      JOIN instructors i ON i.instructor_id = c.instructor_id
      WHERE i.user_id = auth.uid()
    )
  );

-- Backend service-role access fallback for server-side APIs.
CREATE POLICY content_service_role_all ON content
  FOR ALL TO service_role
  USING (TRUE)
  WITH CHECK (TRUE);

-- Students own their enrollments
CREATE POLICY enrollments_self ON enrollments
  USING      (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Students own their progress
CREATE POLICY progress_self ON content_progress
  USING      (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Students own their quiz attempts
CREATE POLICY attempts_self ON quiz_attempts
  USING      (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Students can read/insert answers for their own attempts only.
CREATE POLICY answers_self ON quiz_answers
  USING (
    EXISTS (
      SELECT 1
      FROM quiz_attempts qa
      WHERE qa.attempt_id = quiz_answers.attempt_id
        AND qa.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM quiz_attempts qa
      WHERE qa.attempt_id = quiz_answers.attempt_id
        AND qa.user_id = auth.uid()
    )
  );

-- Backend service-role access fallback for server-side APIs.
CREATE POLICY answers_service_role_all ON quiz_answers
  FOR ALL TO service_role
  USING (TRUE)
  WITH CHECK (TRUE);

-- One-time backfill when running DDL on existing environments:
-- ensure all instructor/admin users have an instructors row.
INSERT INTO instructors (user_id)
SELECT user_id
FROM users
WHERE role IN ('instructor', 'admin')
  AND deleted_at IS NULL
ON CONFLICT (user_id) DO NOTHING;

-- ────────────────────────────────────────────────────────────────────────────
-- SUPABASE AUTH HOOK
-- ────────────────────────────────────────────────────────────────────────────
-- When a user registers via Supabase Auth, this function automatically creates
-- their row in the public.users table. Set this as an Auth Hook in:
-- Supabase Dashboard → Authentication → Hooks → "After user created"
--
-- Alternatively call it from your register endpoint via supabase.auth.signUp()
-- and then insert into public.users with the returned UUID.
--
-- Function is provided here for reference — wire it up in the dashboard.

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.users (user_id, full_name, email, password, role)
  VALUES (
    NEW.id,                                           -- UUID from auth.users
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'User'),
    NEW.email,
    '',                                               -- password managed by Supabase Auth
    COALESCE(NEW.raw_user_meta_data->>'role', 'student')
  )
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- Wire trigger on auth.users (requires elevated privileges in some Supabase setups).
-- If permissions are insufficient, skip gracefully and use Dashboard auth hook instead.
DO $$
BEGIN
  BEGIN
    DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
    CREATE TRIGGER on_auth_user_created
      AFTER INSERT ON auth.users
      FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();
  EXCEPTION
    WHEN insufficient_privilege THEN
      RAISE NOTICE 'Skipping auth.users trigger creation due to insufficient privileges. Configure Authentication > Hooks > After user created to call public.handle_new_auth_user().';
  END;
END;
$$;

